baseURL = "https://plumtree.one/"
languageCode = "en-us"
title = "chorok"
theme = "contrast"
enableEmoji = true

[permalinks]
  posts = "/:year/:month/:title/"

[blackfriday]
  fractions = false

[frontmatter]
  date = ["publishDate", "date", "lastmod"]
