baseURL = "https://plumtree.one/"
languageCode = "en-us"
title = "chorok"
theme = "contrast-green"
enableEmoji = true
watch = true

[permalinks]
  posts = "/:year/:month/:title/"

[frontmatter]
  date = ["publishDate", "date", "lastmod"]

